name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Lint with Black and Ruff
      run: |
        make lint
        
    - name: Run tests
      run: |
        make test
        
    - name: Build package
      run: |
        make quick-build
        
    - name: Validate distribution
      run: |
        make validate-dist
